[plugin]
repository = "https://github.com/VioletStardustXIV/XivGearExport.git"
commit = "6a7d5ec2fd38ddc4fdfc88b2e996cab6e748e312"
owners = ["VioletStardustXIV"]
project_path = "XivGearExport"
changelog = "Initial testing release"