[plugin]
repository = "https://github.com/VioletStardustXIV/XivGearExport.git"
commit = "cce7de64a92e4d686c028fe4a1e3234a66ed5485"
owners = ["VioletStardustXIV"]
project_path = "XivGearExport"
changelog = """
- Updated plugin icon. 
- BLU will now export with a party bonus of 1.
"""
