[plugin]
repository = "https://github.com/VioletStardustXIV/XivGearExport.git"
commit = "7550b6a64067ada70736728c879f9f8fc72315da"
owners = ["VioletStardustXIV"]
project_path = "XivGearExport"
changelog = "Initial testing release"